name: imm-mk-env
channels:
  - conda-forge
dependencies:
  - econtools
  - ipykernel
  - ipython
  - linearmodels
  - matplotlib
  - numpy
  - pip
  - python
  - rich
  - statsmodels
  - toolz
  - pip:
      - stargazer
